name: build & deploy lambda server

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Build source code
        run: npm i typescript && tsc && npm rm typescript
      - name: Install dependencies & Uninstall dependencies not required by lambda
        run: npm i --omit=dev && npm rm dotenv @aws-sdk/client-ses
      - name: Bundle code
        run: zip -r lambda.zip ./node_modules ./dist ./lambda.js ./package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Update Function code
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_NAME }} --zip-file fileb://lambda.zip
